background {
    monitor =
    path = screenshot
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# 1. Relógio (Centro - Parte Superior)
label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = rgba(255, 255, 255, 0.8)
    font_size = 80
    font_family = Go Mono
    position = 0, 80
    halign = center
    valign = center
}

# 2. Campo de Senha (Centro)
input-field {
    monitor =
    size = 220, 45
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.2)
    inner_color = rgba(0, 0, 0, 0.3)
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    placeholder_text = <span foreground="##ffffff88"><i>Senha...</i></span>
    position = 0, -20
    halign = center
    valign = center
}

# 2. Capa da Música (Posicionada à esquerda do texto, abaixo da senha)
image {
    monitor =
    path = /tmp/hyprlock-cover.png
    size = 40 # Tamanho compacto para alinhar com o texto
    rounding = 6
    border_size = 1
    border_color = rgba(255, 255, 255, 0.3)
    
    position = -120, -85 # -120 desloca para a esquerda, -85 coloca abaixo da senha
    halign = center
    valign = center
}

# 3. Nome da Música (Posicionado à direita da capa)
label {
    monitor =
    text = cmd[update:1000] ~/.config/hypr/mpris.sh
    color = rgba(255, 255, 255, 0.75)
    font_size = 11
    font_family = Go Mono
    
    position = 20, -85 # +20 desloca para a direita, mesmo eixo Y (-85) para alinhar lado a lado
    halign = center
    valign = center
}
