-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("HYPRCURSOR_SIZE", "24")

-- Settings
hl.config({
    cursor = {
        enable_hyprcursor = true,
        no_hardware_cursors = 0,
    },
    decoration = {
        blur = {
            contrast = 0.0,
            noise = 0.0,
            size = 9,
        },
        fullscreen_opacity = 0.8,
        rounding = 1,
    },
    dwindle = {
        smart_split = false,
    },
    general = {
        border_size = 2,
        gaps_in = 5,
        layout = "dwindle",
    },
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
})
